apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: titan-platform
  namespace: argocd

spec:
  project: titan

  source:
    repoURL: https://github.com/ArchAndrew/Self-Service-Platform.git 
    targetRevision: main
    path: gitops/apps/titan-platform

  destination:
    server: https://kubernetes.default.svc
    namespace: titan-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true